from datetime import date


ACTIVITIES = [
    {
        "id": 1,
        "name": "Morning Tempo",
        "sport": "Run",
        "date": date(2026, 9, 18),
        "distance_km": 8.4,
        "duration_min": 45.6,
        "avg_pace_min_km": 5.43,
        "avg_heart_rate": 158,
        "max_heart_rate": 174,
        "cadence": 176,
        "elevation_m": 82,
        "training_load": 74,
        "type": "Tempo",
    },
    {
        "id": 2,
        "name": "Easy Base Run",
        "sport": "Run",
        "date": date(2026, 9, 16),
        "distance_km": 6.2,
        "duration_min": 38.4,
        "avg_pace_min_km": 6.19,
        "avg_heart_rate": 142,
        "max_heart_rate": 158,
        "cadence": 170,
        "elevation_m": 41,
        "training_load": 42,
        "type": "Easy",
    },
    {
        "id": 3,
        "name": "Track Intervals",
        "sport": "Run",
        "date": date(2026, 9, 14),
        "distance_km": 7.1,
        "duration_min": 36.1,
        "avg_pace_min_km": 5.08,
        "avg_heart_rate": 164,
        "max_heart_rate": 181,
        "cadence": 181,
        "elevation_m": 24,
        "training_load": 86,
        "type": "Interval",
    },
    {
        "id": 4,
        "name": "Long Run",
        "sport": "Run",
        "date": date(2026, 9, 12),
        "distance_km": 14.3,
        "duration_min": 91.6,
        "avg_pace_min_km": 6.41,
        "avg_heart_rate": 148,
        "max_heart_rate": 165,
        "cadence": 168,
        "elevation_m": 116,
        "training_load": 79,
        "type": "Long Run",
    },
    {
        "id": 5,
        "name": "Recovery Jog",
        "sport": "Run",
        "date": date(2026, 9, 10),
        "distance_km": 4.5,
        "duration_min": 30.2,
        "avg_pace_min_km": 6.71,
        "avg_heart_rate": 136,
        "max_heart_rate": 149,
        "cadence": 166,
        "elevation_m": 18,
        "training_load": 25,
        "type": "Recovery",
    },
    {
        "id": 6,
        "name": "Pool Session",
        "sport": "Swim",
        "date": date(2026, 9, 8),
        "distance_km": 2.0,
        "duration_min": 45.0,
        "avg_pace_min_km": 22.5,
        "avg_heart_rate": 132,
        "max_heart_rate": 151,
        "cadence": 0,
        "elevation_m": 0,
        "training_load": 31,
        "type": "Swimming",
    },
]


TRAINING_PLAN = [
    {"day": "Mon", "date": "Sep 21", "type": "Tempo", "title": "Controlled tempo", "detail": "3 x 8 min at comfortably hard effort", "status": "planned"},
    {"day": "Tue", "date": "Sep 22", "type": "Interval", "title": "Speed intervals", "detail": "6 x 400 m, full relaxed recovery", "status": "planned"},
    {"day": "Wed", "date": "Sep 23", "type": "Easy", "title": "Easy aerobic run", "detail": "35 min conversational effort", "status": "next"},
    {"day": "Thu", "date": "Sep 24", "type": "Strength", "title": "Runner strength", "detail": "30 min hips, calves, and core", "status": "planned"},
    {"day": "Fri", "date": "Sep 25", "type": "Rest", "title": "Full rest", "detail": "Light walking is optional", "status": "rest"},
    {"day": "Sat", "date": "Sep 26", "type": "Quality", "title": "Quality session", "detail": "Adjust intensity after recovery check", "status": "planned"},
    {"day": "Sun", "date": "Sep 27", "type": "Swimming", "title": "Easy swimming", "detail": "45 min relaxed technique work", "status": "planned"},
]
